package com.nsn.telkomsel.mics.hbm;

// Generated Mar 28, 2013 6:12:03 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Announcement generated by hbm2java
 */
public class Announcement implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3656078251652914784L;
	private String announcementKey;
	private String companyId;
	private Integer annoId;
	private String shortDescription;
	private String description;
	private Integer srfelementId;
	private String updateUser;
	private Date updateTimestamp;

	public Announcement() {
	}

	public Announcement(String announcementKey) {
		this.announcementKey = announcementKey;
	}

	public Announcement(String announcementKey, String companyId,
			Integer annoId, String shortDescription, String description,
			Integer srfelementId, String updateUser, Date updateTimestamp) {
		this.announcementKey = announcementKey;
		this.companyId = companyId;
		this.annoId = annoId;
		this.shortDescription = shortDescription;
		this.description = description;
		this.srfelementId = srfelementId;
		this.updateUser = updateUser;
		this.updateTimestamp = updateTimestamp;
	}

	public String getAnnouncementKey() {
		return this.announcementKey;
	}

	public void setAnnouncementKey(String announcementKey) {
		this.announcementKey = announcementKey;
	}

	public String getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	public Integer getAnnoId() {
		return this.annoId;
	}

	public void setAnnoId(Integer annoId) {
		this.annoId = annoId;
	}

	public String getShortDescription() {
		return this.shortDescription;
	}

	public void setShortDescription(String shortDescription) {
		this.shortDescription = shortDescription;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getSrfelementId() {
		return this.srfelementId;
	}

	public void setSrfelementId(Integer srfelementId) {
		this.srfelementId = srfelementId;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTimestamp() {
		return this.updateTimestamp;
	}

	public void setUpdateTimestamp(Date updateTimestamp) {
		this.updateTimestamp = updateTimestamp;
	}

}
