package com.nsn.telkomsel.mics.hbm;

// Generated Mar 28, 2013 6:12:03 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Callscreening generated by hbm2java
 */
public class Callscreening implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8866925230258670253L;
	private String callScreeningKey;
	private Integer type;
	private Integer level;
	private String updateUser;
	private Date updateTimestamp;
	private String companyKey;

	public Callscreening() {
	}

	public Callscreening(String callScreeningKey, String updateUser) {
		this.callScreeningKey = callScreeningKey;
		this.updateUser = updateUser;
	}

	public Callscreening(String callScreeningKey, Integer type, Integer level,
			String updateUser, Date updateTimestamp) {
		this.callScreeningKey = callScreeningKey;
		this.type = type;
		this.level = level;
		this.updateUser = updateUser;
		this.updateTimestamp = updateTimestamp;
	}

	public String getCallScreeningKey() {
		return this.callScreeningKey;
	}

	public void setCallScreeningKey(String callScreeningKey) {
		this.callScreeningKey = callScreeningKey;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTimestamp() {
		return this.updateTimestamp;
	}

	public void setUpdateTimestamp(Date updateTimestamp) {
		this.updateTimestamp = updateTimestamp;
	}

	public String getCompanyKey() {
		return companyKey;
	}

	public void setCompanyKey(String companyKey) {
		this.companyKey = companyKey;
	}
	
	

}
