package com.nsn.telkomsel.mics.hbm;

// Generated Mar 28, 2013 6:12:03 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Community generated by hbm2java
 */
public class Community implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1691836618256979308L;
	private String communityKey;
	private String communityName;
	private String contactPerson;
	private String address;
	private String updateUser;
	private Date updateTimestampt;

	public Community() {
	}

	public Community(String communityKey, String communityName,
			String updateUser, Date updateTimestampt) {
		this.communityKey = communityKey;
		this.communityName = communityName;
		this.updateUser = updateUser;
		this.updateTimestampt = updateTimestampt;
	}

	public Community(String communityKey, String communityName,
			String contactPerson, String address, String updateUser,
			Date updateTimestampt) {
		this.communityKey = communityKey;
		this.communityName = communityName;
		this.contactPerson = contactPerson;
		this.address = address;
		this.updateUser = updateUser;
		this.updateTimestampt = updateTimestampt;
	}

	public String getCommunityKey() {
		return this.communityKey;
	}

	public void setCommunityKey(String communityKey) {
		this.communityKey = communityKey;
	}

	public String getCommunityName() {
		return this.communityName;
	}

	public void setCommunityName(String communityName) {
		this.communityName = communityName;
	}

	public String getContactPerson() {
		return this.contactPerson;
	}

	public void setContactPerson(String contactPerson) {
		this.contactPerson = contactPerson;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTimestampt() {
		return this.updateTimestampt;
	}

	public void setUpdateTimestampt(Date updateTimestampt) {
		this.updateTimestampt = updateTimestampt;
	}

}
