package com.nsn.telkomsel.mics.hbm;

// Generated Mar 28, 2013 6:12:03 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Communitymember generated by hbm2java
 */
public class Communitymember implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2825469061969192575L;
	private String communityMemberKey;
	private String communityName;
	private String userKey;
	private String updateUser;
	private Date updateTimestamp;

	public Communitymember() {
	}

	public Communitymember(String communityMemberKey, String updateUser,
			Date updateTimestamp) {
		this.communityMemberKey = communityMemberKey;
		this.updateUser = updateUser;
		this.updateTimestamp = updateTimestamp;
	}

	public Communitymember(String communityMemberKey, String communityName,
			String userKey, String updateUser, Date updateTimestamp) {
		this.communityMemberKey = communityMemberKey;
		this.communityName = communityName;
		this.userKey = userKey;
		this.updateUser = updateUser;
		this.updateTimestamp = updateTimestamp;
	}

	public String getCommunityMemberKey() {
		return this.communityMemberKey;
	}

	public void setCommunityMemberKey(String communityMemberKey) {
		this.communityMemberKey = communityMemberKey;
	}

	public String getCommunityName() {
		return this.communityName;
	}

	public void setCommunityName(String communityName) {
		this.communityName = communityName;
	}

	public String getUserKey() {
		return this.userKey;
	}

	public void setUserKey(String userKey) {
		this.userKey = userKey;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTimestamp() {
		return this.updateTimestamp;
	}

	public void setUpdateTimestamp(Date updateTimestamp) {
		this.updateTimestamp = updateTimestamp;
	}

}
