package com.nsn.telkomsel.mics.hbm;

// Generated Mar 28, 2013 6:12:03 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Group generated by hbm2java
 */
public class Group implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4761821806231864123L;
	private String groupKey;
	private String companyId;
	private int groupId;
	private String groupName;
	private String groupCli;
	private String incomingCallScreening;
	private String outgoingCallScreening;
	private String updateUser;
	private Date updateTimestamp;

	public Group() {
	}

	public Group(String groupKey, String companyId, int groupId,
			String groupName, String updateUser, Date updateTimestamp) {
		this.groupKey = groupKey;
		this.companyId = companyId;
		this.groupId = groupId;
		this.groupName = groupName;
		this.updateUser = updateUser;
		this.updateTimestamp = updateTimestamp;
	}

	public Group(String groupKey, String companyId, int groupId,
			String groupName, String groupCli, String incomingCallScreening,
			String outgoingCallScreening, String updateUser,
			Date updateTimestamp) {
		this.groupKey = groupKey;
		this.companyId = companyId;
		this.groupId = groupId;
		this.groupName = groupName;
		this.groupCli = groupCli;
		this.incomingCallScreening = incomingCallScreening;
		this.outgoingCallScreening = outgoingCallScreening;
		this.updateUser = updateUser;
		this.updateTimestamp = updateTimestamp;
	}

	public String getGroupKey() {
		return this.groupKey;
	}

	public void setGroupKey(String groupKey) {
		this.groupKey = groupKey;
	}

	public String getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public String getGroupCli() {
		return this.groupCli;
	}

	public void setGroupCli(String groupCli) {
		this.groupCli = groupCli;
	}

	public String getIncomingCallScreening() {
		return this.incomingCallScreening;
	}

	public void setIncomingCallScreening(String incomingCallScreening) {
		this.incomingCallScreening = incomingCallScreening;
	}

	public String getOutgoingCallScreening() {
		return this.outgoingCallScreening;
	}

	public void setOutgoingCallScreening(String outgoingCallScreening) {
		this.outgoingCallScreening = outgoingCallScreening;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTimestamp() {
		return this.updateTimestamp;
	}

	public void setUpdateTimestamp(Date updateTimestamp) {
		this.updateTimestamp = updateTimestamp;
	}

}
