package com.nsn.telkomsel.mics.hbm;

// Generated Mar 28, 2013 6:12:03 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Huntingschedule generated by hbm2java
 */
public class Huntingschedule implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4715125249454983721L;
	private String huntingScheduleKey;
	private Integer orderIndex;
	private String huntingGroupKey;
	private String timeBandKey;
	private String updateUser;
	private Date updateTimestampt;

	public Huntingschedule() {
	}

	public Huntingschedule(String huntingScheduleKey, String updateUser,
			Date updateTimestampt) {
		this.huntingScheduleKey = huntingScheduleKey;
		this.updateUser = updateUser;
		this.updateTimestampt = updateTimestampt;
	}

	public Huntingschedule(String huntingScheduleKey, Integer orderIndex,
			String huntingGroupKey, String timeBandKey, String updateUser,
			Date updateTimestampt) {
		this.huntingScheduleKey = huntingScheduleKey;
		this.orderIndex = orderIndex;
		this.huntingGroupKey = huntingGroupKey;
		this.timeBandKey = timeBandKey;
		this.updateUser = updateUser;
		this.updateTimestampt = updateTimestampt;
	}

	public String getHuntingScheduleKey() {
		return this.huntingScheduleKey;
	}

	public void setHuntingScheduleKey(String huntingScheduleKey) {
		this.huntingScheduleKey = huntingScheduleKey;
	}

	public Integer getOrderIndex() {
		return this.orderIndex;
	}

	public void setOrderIndex(Integer orderIndex) {
		this.orderIndex = orderIndex;
	}

	public String getHuntingGroupKey() {
		return this.huntingGroupKey;
	}

	public void setHuntingGroupKey(String huntingGroupKey) {
		this.huntingGroupKey = huntingGroupKey;
	}

	public String getTimeBandKey() {
		return this.timeBandKey;
	}

	public void setTimeBandKey(String timeBandKey) {
		this.timeBandKey = timeBandKey;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTimestampt() {
		return this.updateTimestampt;
	}

	public void setUpdateTimestampt(Date updateTimestampt) {
		this.updateTimestampt = updateTimestampt;
	}

}
