package com.nsn.telkomsel.mics.hbm;

// Generated Mar 28, 2013 6:12:03 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Numbertranslation generated by hbm2java
 */
public class Numbertranslation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -500552903985818879L;
	private String numberTranslationKey;
	private String companyId;
	private String inPrefix;
	private Integer minLength;
	private Integer maxLength;
	private Integer trimDigits;
	private String outPrefix;
	private Integer calledPartyType;
	private Integer orderIndex;
	private String updateUser;
	private Date updateTimestamp;

	public Numbertranslation() {
	}

	public Numbertranslation(String numberTranslationKey, String updateUser) {
		this.numberTranslationKey = numberTranslationKey;
		this.updateUser = updateUser;
	}

	public Numbertranslation(String numberTranslationKey, String companyId,
			String inPrefix, Integer minLength, Integer maxLength,
			Integer trimDigits, String outPrefix, Integer calledPartyType,
			Integer orderIndex, String updateUser, Date updateTimestamp) {
		this.numberTranslationKey = numberTranslationKey;
		this.companyId = companyId;
		this.inPrefix = inPrefix;
		this.minLength = minLength;
		this.maxLength = maxLength;
		this.trimDigits = trimDigits;
		this.outPrefix = outPrefix;
		this.calledPartyType = calledPartyType;
		this.orderIndex = orderIndex;
		this.updateUser = updateUser;
		this.updateTimestamp = updateTimestamp;
	}

	public String getNumberTranslationKey() {
		return this.numberTranslationKey;
	}

	public void setNumberTranslationKey(String numberTranslationKey) {
		this.numberTranslationKey = numberTranslationKey;
	}

	public String getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	public String getInPrefix() {
		return this.inPrefix;
	}

	public void setInPrefix(String inPrefix) {
		this.inPrefix = inPrefix;
	}

	public Integer getMinLength() {
		return this.minLength;
	}

	public void setMinLength(Integer minLength) {
		this.minLength = minLength;
	}

	public Integer getMaxLength() {
		return this.maxLength;
	}

	public void setMaxLength(Integer maxLength) {
		this.maxLength = maxLength;
	}

	public Integer getTrimDigits() {
		return this.trimDigits;
	}

	public void setTrimDigits(Integer trimDigits) {
		this.trimDigits = trimDigits;
	}

	public String getOutPrefix() {
		return this.outPrefix;
	}

	public void setOutPrefix(String outPrefix) {
		this.outPrefix = outPrefix;
	}

	public Integer getCalledPartyType() {
		return this.calledPartyType;
	}

	public void setCalledPartyType(Integer calledPartyType) {
		this.calledPartyType = calledPartyType;
	}

	public Integer getOrderIndex() {
		return this.orderIndex;
	}

	public void setOrderIndex(Integer orderIndex) {
		this.orderIndex = orderIndex;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTimestamp() {
		return this.updateTimestamp;
	}

	public void setUpdateTimestamp(Date updateTimestamp) {
		this.updateTimestamp = updateTimestamp;
	}

}
