package com.nsn.telkomsel.mics.hbm;

// Generated Mar 28, 2013 6:12:03 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Number generated by hbm2java
 */
public class Number implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4570086426034414760L;
	private String numberKey;
	private String companyId;
	private String userKey;
	private Integer orderIndex;
	private String publicNumber;
	private String privateNumber;
	private Integer numberType;
	private String lastAnswer;
	private String updateUser;
	private Date updateTimestamp;

	public Number() {
	}

	public Number(String numberKey, String companyId, String userKey) {
		this.numberKey = numberKey;
		this.companyId = companyId;
		this.userKey = userKey;
	}

	public Number(String numberKey, String companyId, String userKey,
			Integer orderIndex, String publicNumber, String privateNumber,
			Integer numberType, String lastAnswer, String updateUser,
			Date updateTimestamp) {
		this.numberKey = numberKey;
		this.companyId = companyId;
		this.userKey = userKey;
		this.orderIndex = orderIndex;
		this.publicNumber = publicNumber;
		this.privateNumber = privateNumber;
		this.numberType = numberType;
		this.lastAnswer = lastAnswer;
		this.updateUser = updateUser;
		this.updateTimestamp = updateTimestamp;
	}

	public String getNumberKey() {
		return this.numberKey;
	}

	public void setNumberKey(String numberKey) {
		this.numberKey = numberKey;
	}

	public String getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	public String getUserKey() {
		return this.userKey;
	}

	public void setUserKey(String userKey) {
		this.userKey = userKey;
	}

	public Integer getOrderIndex() {
		return this.orderIndex;
	}

	public void setOrderIndex(Integer orderIndex) {
		this.orderIndex = orderIndex;
	}

	public String getPublicNumber() {
		return this.publicNumber;
	}

	public void setPublicNumber(String publicNumber) {
		this.publicNumber = publicNumber;
	}

	public String getPrivateNumber() {
		return this.privateNumber;
	}

	public void setPrivateNumber(String privateNumber) {
		this.privateNumber = privateNumber;
	}

	public Integer getNumberType() {
		return this.numberType;
	}

	public void setNumberType(Integer numberType) {
		this.numberType = numberType;
	}

	public String getLastAnswer() {
		return this.lastAnswer;
	}

	public void setLastAnswer(String lastAnswer) {
		this.lastAnswer = lastAnswer;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTimestamp() {
		return this.updateTimestamp;
	}

	public void setUpdateTimestamp(Date updateTimestamp) {
		this.updateTimestamp = updateTimestamp;
	}

}
