package com.nsn.telkomsel.mics.hbm;

// Generated Mar 28, 2013 6:12:03 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Partnership generated by hbm2java
 */
public class Partnership implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4777443777356239534L;
	private String partnershipKey;
	private String partnershipName;
	private String companyId1;
	private String companyId2;
	private String updateUser;
	private Date updateTimestamp;

	public Partnership() {
	}

	public Partnership(String partnershipKey, String partnershipName,
			String updateUser, Date updateTimestamp) {
		this.partnershipKey = partnershipKey;
		this.partnershipName = partnershipName;
		this.updateUser = updateUser;
		this.updateTimestamp = updateTimestamp;
	}

	public Partnership(String partnershipKey, String partnershipName,
			String companyId1, String companyId2, String updateUser,
			Date updateTimestamp) {
		this.partnershipKey = partnershipKey;
		this.partnershipName = partnershipName;
		this.companyId1 = companyId1;
		this.companyId2 = companyId2;
		this.updateUser = updateUser;
		this.updateTimestamp = updateTimestamp;
	}

	public String getPartnershipKey() {
		return this.partnershipKey;
	}

	public void setPartnershipKey(String partnershipKey) {
		this.partnershipKey = partnershipKey;
	}

	public String getPartnershipName() {
		return this.partnershipName;
	}

	public void setPartnershipName(String partnershipName) {
		this.partnershipName = partnershipName;
	}

	public String getCompanyId1() {
		return this.companyId1;
	}

	public void setCompanyId1(String companyId1) {
		this.companyId1 = companyId1;
	}

	public String getCompanyId2() {
		return this.companyId2;
	}

	public void setCompanyId2(String companyId2) {
		this.companyId2 = companyId2;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTimestamp() {
		return this.updateTimestamp;
	}

	public void setUpdateTimestamp(Date updateTimestamp) {
		this.updateTimestamp = updateTimestamp;
	}

}
