package com.nsn.telkomsel.mics.hbm;

// Generated Mar 28, 2013 6:12:03 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Switchboardmenu generated by hbm2java
 */
public class Switchboardmenu implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -569335330323740750L;
	private String switchboardMenuKey;
	private String switchboardKey;
	private Integer dialDigit;
	private String description;
	private Integer menuType;
	private String destinationNumber;
	private Integer annoId;
	private Integer upMenuDialDigit;
	private String updateUser;
	private Date updateTimestamp;

	public Switchboardmenu() {
	}

	public Switchboardmenu(String switchboardMenuKey, String updateUser,
			Date updateTimestamp) {
		this.switchboardMenuKey = switchboardMenuKey;
		this.updateUser = updateUser;
		this.updateTimestamp = updateTimestamp;
	}

	public Switchboardmenu(String switchboardMenuKey, String switchboardKey,
			Integer dialDigit, String description, Integer menuType,
			String destinationNumber, Integer annoId, Integer upMenuDialDigit,
			String updateUser, Date updateTimestamp) {
		this.switchboardMenuKey = switchboardMenuKey;
		this.switchboardKey = switchboardKey;
		this.dialDigit = dialDigit;
		this.description = description;
		this.menuType = menuType;
		this.destinationNumber = destinationNumber;
		this.annoId = annoId;
		this.upMenuDialDigit = upMenuDialDigit;
		this.updateUser = updateUser;
		this.updateTimestamp = updateTimestamp;
	}

	public String getSwitchboardMenuKey() {
		return this.switchboardMenuKey;
	}

	public void setSwitchboardMenuKey(String switchboardMenuKey) {
		this.switchboardMenuKey = switchboardMenuKey;
	}

	public String getSwitchboardKey() {
		return this.switchboardKey;
	}

	public void setSwitchboardKey(String switchboardKey) {
		this.switchboardKey = switchboardKey;
	}

	public Integer getDialDigit() {
		return this.dialDigit;
	}

	public void setDialDigit(Integer dialDigit) {
		this.dialDigit = dialDigit;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getMenuType() {
		return this.menuType;
	}

	public void setMenuType(Integer menuType) {
		this.menuType = menuType;
	}

	public String getDestinationNumber() {
		return this.destinationNumber;
	}

	public void setDestinationNumber(String destinationNumber) {
		this.destinationNumber = destinationNumber;
	}

	public Integer getAnnoId() {
		return this.annoId;
	}

	public void setAnnoId(Integer annoId) {
		this.annoId = annoId;
	}

	public Integer getUpMenuDialDigit() {
		return this.upMenuDialDigit;
	}

	public void setUpMenuDialDigit(Integer upMenuDialDigit) {
		this.upMenuDialDigit = upMenuDialDigit;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTimestamp() {
		return this.updateTimestamp;
	}

	public void setUpdateTimestamp(Date updateTimestamp) {
		this.updateTimestamp = updateTimestamp;
	}

}
