package com.nsn.telkomsel.mics.hbm;

// Generated Mar 28, 2013 6:12:03 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1472254858968624116L;
	private String userKey;
	private String mainPrivateNumber;
	private String mainPublicNumber;
	private String companyId;
	private Integer groupId;
	private Integer subGroupId;
	private String userGroupId;
	private String userName;
	private Integer userType;
	private Boolean locked;
	private Boolean userNumberAsCli;
	private Boolean userNumberAsChargedParty;
	private Integer huntingOption;
	private Boolean keepHuntingOnBusy;
	private Boolean reverseCharging;
	private String incomingCallScreening;
	private String outgoingCallScreening;
	private Boolean enableAnnoRecording;
	private String pin;
	private Integer language;
	private String updateUser;
	private Date updateTimestamp;

	public User() {
	}

	public User(String userKey, String mainPublicNumber, String companyId,
			String updateUser, Date updateTimestamp) {
		this.userKey = userKey;
		this.mainPublicNumber = mainPublicNumber;
		this.companyId = companyId;
		this.updateUser = updateUser;
		this.updateTimestamp = updateTimestamp;
	}

	public User(String userKey, String mainPrivateNumber,
			String mainPublicNumber, String companyId, Integer groupId,
			Integer subGroupId, String userGroupId, String userName,
			Integer userType, Boolean locked, Boolean userNumberAsCli,
			Boolean userNumberAsChargedParty, Integer huntingOption,
			Boolean keepHuntingOnBusy, String incomingCallScreening,
			String outgoingCallScreening, Boolean enableAnnoRecording,
			String pin, Integer language, String updateUser,
			Date updateTimestamp,Boolean reverseCharging) {
		this.userKey = userKey;
		this.mainPrivateNumber = mainPrivateNumber;
		this.mainPublicNumber = mainPublicNumber;
		this.companyId = companyId;
		this.groupId = groupId;
		this.subGroupId = subGroupId;
		this.userGroupId = userGroupId;
		this.userName = userName;
		this.userType = userType;
		this.locked = locked;
		this.userNumberAsCli = userNumberAsCli;
		this.userNumberAsChargedParty = userNumberAsChargedParty;
		this.huntingOption = huntingOption;
		this.keepHuntingOnBusy = keepHuntingOnBusy;
		this.incomingCallScreening = incomingCallScreening;
		this.outgoingCallScreening = outgoingCallScreening;
		this.enableAnnoRecording = enableAnnoRecording;
		this.pin = pin;
		this.language = language;
		this.updateUser = updateUser;
		this.updateTimestamp = updateTimestamp;
		this.reverseCharging= reverseCharging;
	}

	public String getUserKey() {
		return this.userKey;
	}

	public void setUserKey(String userKey) {
		this.userKey = userKey;
	}

	public String getMainPrivateNumber() {
		return this.mainPrivateNumber;
	}

	public void setMainPrivateNumber(String mainPrivateNumber) {
		this.mainPrivateNumber = mainPrivateNumber;
	}

	public String getMainPublicNumber() {
		return this.mainPublicNumber;
	}

	public void setMainPublicNumber(String mainPublicNumber) {
		this.mainPublicNumber = mainPublicNumber;
	}

	public String getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	public Integer getSubGroupId() {
		return this.subGroupId;
	}

	public void setSubGroupId(Integer subGroupId) {
		this.subGroupId = subGroupId;
	}

	public String getUserGroupId() {
		return this.userGroupId;
	}

	public void setUserGroupId(String userGroupId) {
		this.userGroupId = userGroupId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Integer getUserType() {
		return this.userType;
	}

	public void setUserType(Integer userType) {
		this.userType = userType;
	}

	public Boolean getLocked() {
		return this.locked;
	}

	public void setLocked(Boolean locked) {
		this.locked = locked;
	}

	public Boolean getUserNumberAsCli() {
		return this.userNumberAsCli;
	}

	public void setUserNumberAsCli(Boolean userNumberAsCli) {
		this.userNumberAsCli = userNumberAsCli;
	}

	public Boolean getUserNumberAsChargedParty() {
		return this.userNumberAsChargedParty;
	}

	public void setUserNumberAsChargedParty(Boolean userNumberAsChargedParty) {
		this.userNumberAsChargedParty = userNumberAsChargedParty;
	}

	public Integer getHuntingOption() {
		return this.huntingOption;
	}

	public void setHuntingOption(Integer huntingOption) {
		this.huntingOption = huntingOption;
	}

	public Boolean getKeepHuntingOnBusy() {
		return this.keepHuntingOnBusy;
	}

	public void setKeepHuntingOnBusy(Boolean keepHuntingOnBusy) {
		this.keepHuntingOnBusy = keepHuntingOnBusy;
	}

	/**
	 * @return the reverseCharging
	 */
	public Boolean getReverseCharging() {
		return reverseCharging;
	}

	/**
	 * @param reverseCharging the reverseCharging to set
	 */
	public void setReverseCharging(Boolean reverseCharging) {
		this.reverseCharging = reverseCharging;
	}

	public String getIncomingCallScreening() {
		return this.incomingCallScreening;
	}

	public void setIncomingCallScreening(String incomingCallScreening) {
		this.incomingCallScreening = incomingCallScreening;
	}

	public String getOutgoingCallScreening() {
		return this.outgoingCallScreening;
	}

	public void setOutgoingCallScreening(String outgoingCallScreening) {
		this.outgoingCallScreening = outgoingCallScreening;
	}

	public Boolean getEnableAnnoRecording() {
		return this.enableAnnoRecording;
	}

	public void setEnableAnnoRecording(Boolean enableAnnoRecording) {
		this.enableAnnoRecording = enableAnnoRecording;
	}

	public String getPin() {
		return this.pin;
	}

	public void setPin(String pin) {
		this.pin = pin;
	}

	public Integer getLanguage() {
		return this.language;
	}

	public void setLanguage(Integer language) {
		this.language = language;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTimestamp() {
		return this.updateTimestamp;
	}

	public void setUpdateTimestamp(Date updateTimestamp) {
		this.updateTimestamp = updateTimestamp;
	}

}
