package com.nsn.telkomsel.mics.hbm;

// Generated Mar 28, 2013 6:12:03 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * WebuserRole generated by hbm2java
 */
public class WebuserRole implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7128556989661215622L;
	private int webUserRoleKey;
	private Integer webUserKey;
	private Integer roleKey;
	private String updateUser;
	private Date updateTimestamp;

	public WebuserRole() {
	}

	public WebuserRole(int webUserRoleKey, String updateUser,
			Date updateTimestamp) {
		this.webUserRoleKey = webUserRoleKey;
		this.updateUser = updateUser;
		this.updateTimestamp = updateTimestamp;
	}

	public WebuserRole(int webUserRoleKey, Integer webUserKey, Integer roleKey,
			String updateUser, Date updateTimestamp) {
		this.webUserRoleKey = webUserRoleKey;
		this.webUserKey = webUserKey;
		this.roleKey = roleKey;
		this.updateUser = updateUser;
		this.updateTimestamp = updateTimestamp;
	}

	public int getWebUserRoleKey() {
		return this.webUserRoleKey;
	}

	public void setWebUserRoleKey(int webUserRoleKey) {
		this.webUserRoleKey = webUserRoleKey;
	}

	public Integer getWebUserKey() {
		return this.webUserKey;
	}

	public void setWebUserKey(Integer webUserKey) {
		this.webUserKey = webUserKey;
	}

	public Integer getRoleKey() {
		return this.roleKey;
	}

	public void setRoleKey(Integer roleKey) {
		this.roleKey = roleKey;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTimestamp() {
		return this.updateTimestamp;
	}

	public void setUpdateTimestamp(Date updateTimestamp) {
		this.updateTimestamp = updateTimestamp;
	}

}
