package com.nsn.telkomsel.mics.hbm;

// Generated Mar 28, 2013 6:12:03 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Webuser generated by hbm2java
 */
public class Webuser implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3221024766925920240L;
	private int webUserKey;
	private int roleKey;
	private String userName;
	private String password;
	private String token;
	private String companyKey;
	private String updateUser;
	private Date updateTimestamp;

	public Webuser() {
	}

	public Webuser(int webUserKey, String updateUser, Date updateTimestamp) {
		this.webUserKey = webUserKey;
		this.updateUser = updateUser;
		this.updateTimestamp = updateTimestamp;
	}

	public Webuser(int webUserKey, String userName, String password,
			String token, String companyKey, int roleKey, String updateUser, Date updateTimestamp) {
		this.webUserKey = webUserKey;
		this.userName = userName;
		this.password = password;
		this.token = token;
		this.companyKey = companyKey;
		this.roleKey = roleKey;
		this.updateUser = updateUser;
		this.updateTimestamp = updateTimestamp;
	}

	public int getWebUserKey() {
		return this.webUserKey;
	}

	public void setWebUserKey(int webUserKey) {
		this.webUserKey = webUserKey;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTimestamp() {
		return this.updateTimestamp;
	}

	public void setUpdateTimestamp(Date updateTimestamp) {
		this.updateTimestamp = updateTimestamp;
	}

	public String getCompanyKey() {
		return companyKey;
	}

	public void setCompanyKey(String companyKey) {
		this.companyKey = companyKey;
	}

	public int getRoleKey() {
		return roleKey;
	}

	public void setRoleKey(int roleKey) {
		this.roleKey = roleKey;
	}
	
	

}
