package com.nsn.telkomsel.mics.orahbm;

// Generated May 9, 2013 1:29:08 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.sql.Timestamp;

import org.apache.log4j.Logger;

/**
 * Company generated by hbm2java
 */
public class Company implements java.io.Serializable {


	private static final long serialVersionUID = 7105620508796061217L;
	private String companykey;
	private String companyname;
	private String contactperson;
	private String email;
	private String address;
	private String domainname;
	private String chargestring;
	private BigDecimal locked;
	private BigDecimal enableforcedonnet;
	private BigDecimal enablegrouphunting;
	private BigDecimal enableprivatecall;
	private String companycli;
	private String usemaincliprefix;
	private BigDecimal clioption;
	private BigDecimal enablevpnchargingforsms;
	private String defaultincs;
	private String defaultincsdesc;
	private String bypassdefaultincs;
	private String forcedincs;
	private String forcedincsdesc;
	private String bypassforcedincs;
	private String defaultoutcs;
	private String defaultoutcsdesc;
	private String bypassdefaultoutcs;
	private String forcedoutcs;
	private String forcedoutcsdesc;
	private String bypassforcedoutcs;
	private String updateuser;
	private Timestamp updatetimestamp;

	public Company() {
	}

	public Company(String companykey, String companyname, String contactperson,
			String updateuser, Timestamp updatetimestamp) {
		this.companykey = companykey;
		this.companyname = companyname;
		this.contactperson = contactperson;
		this.updateuser = updateuser;
		this.updatetimestamp = updatetimestamp;
	}

	public Company(String companykey, String companyname, String contactperson,
			String email, String address, String domainname,String chargestring,
			BigDecimal locked, BigDecimal enableforcedonnet,
			BigDecimal enablegrouphunting, BigDecimal enableprivatecall,
			String companycli, String usemaincliprefix, BigDecimal clioption,
			String defaultincs, String defaultincsdesc,
			String bypassdefaultincs, String forcedincs, String forcedincsdesc,
			String bypassforcedincs, String defaultoutcs,
			String defaultoutcsdesc, String bypassdefaultoutcs,
			String forcedoutcs, String forcedoutcsdesc,
			String bypassforcedoutcs, String updateuser,
			Timestamp updatetimestamp) {
		this.companykey = companykey;
		this.companyname = companyname;
		this.contactperson = contactperson;
		this.email = email;
		this.address = address;
		this.domainname = domainname;
		this.chargestring = chargestring;
		this.locked = locked;
		this.enableforcedonnet = enableforcedonnet;
		this.enablegrouphunting = enablegrouphunting;
		this.enableprivatecall = enableprivatecall;
		this.companycli = companycli;
		this.usemaincliprefix = usemaincliprefix;
		this.clioption = clioption;
		this.defaultincs = defaultincs;
		this.defaultincsdesc = defaultincsdesc;
		this.bypassdefaultincs = bypassdefaultincs;
		this.forcedincs = forcedincs;
		this.forcedincsdesc = forcedincsdesc;
		this.bypassforcedincs = bypassforcedincs;
		this.defaultoutcs = defaultoutcs;
		this.defaultoutcsdesc = defaultoutcsdesc;
		this.bypassdefaultoutcs = bypassdefaultoutcs;
		this.forcedoutcs = forcedoutcs;
		this.forcedoutcsdesc = forcedoutcsdesc;
		this.bypassforcedoutcs = bypassforcedoutcs;
		this.updateuser = updateuser;
		this.updatetimestamp = updatetimestamp;
	}
	
	

	/**
	 * @param companykey
	 * @param companyname
	 * @param contactperson
	 * @param email
	 * @param address
	 * @param domainname
	 * @param chargestring
	 * @param locked
	 * @param enableforcedonnet
	 * @param enablegrouphunting
	 * @param enableprivatecall
	 * @param companycli
	 * @param usemaincliprefix
	 * @param clioption
	 * @param enablevpnchargingforsms
	 * @param defaultincs
	 * @param defaultincsdesc
	 * @param bypassdefaultincs
	 * @param forcedincs
	 * @param forcedincsdesc
	 * @param bypassforcedincs
	 * @param defaultoutcs
	 * @param defaultoutcsdesc
	 * @param bypassdefaultoutcs
	 * @param forcedoutcs
	 * @param forcedoutcsdesc
	 * @param bypassforcedoutcs
	 * @param updateuser
	 * @param updatetimestamp
	 */
	public Company(String companykey, String companyname, String contactperson,
			String email, String address, String domainname,
			String chargestring, BigDecimal locked,
			BigDecimal enableforcedonnet, BigDecimal enablegrouphunting,
			BigDecimal enableprivatecall, String companycli,
			String usemaincliprefix, BigDecimal clioption,
			BigDecimal enablevpnchargingforsms, String defaultincs,
			String defaultincsdesc, String bypassdefaultincs,
			String forcedincs, String forcedincsdesc, String bypassforcedincs,
			String defaultoutcs, String defaultoutcsdesc,
			String bypassdefaultoutcs, String forcedoutcs,
			String forcedoutcsdesc, String bypassforcedoutcs,
			String updateuser, Timestamp updatetimestamp) {
		super();
		this.companykey = companykey;
		this.companyname = companyname;
		this.contactperson = contactperson;
		this.email = email;
		this.address = address;
		this.domainname = domainname;
		this.chargestring = chargestring;
		this.locked = locked;
		this.enableforcedonnet = enableforcedonnet;
		this.enablegrouphunting = enablegrouphunting;
		this.enableprivatecall = enableprivatecall;
		this.companycli = companycli;
		this.usemaincliprefix = usemaincliprefix;
		this.clioption = clioption;
		this.enablevpnchargingforsms = enablevpnchargingforsms;
		this.defaultincs = defaultincs;
		this.defaultincsdesc = defaultincsdesc;
		this.bypassdefaultincs = bypassdefaultincs;
		this.forcedincs = forcedincs;
		this.forcedincsdesc = forcedincsdesc;
		this.bypassforcedincs = bypassforcedincs;
		this.defaultoutcs = defaultoutcs;
		this.defaultoutcsdesc = defaultoutcsdesc;
		this.bypassdefaultoutcs = bypassdefaultoutcs;
		this.forcedoutcs = forcedoutcs;
		this.forcedoutcsdesc = forcedoutcsdesc;
		this.bypassforcedoutcs = bypassforcedoutcs;
		this.updateuser = updateuser;
		this.updatetimestamp = updatetimestamp;
	}

	public String getCompanykey() {
		return this.companykey;
	}

	public void setCompanykey(String companykey) {
		this.companykey = companykey;
	}

	public String getCompanyname() {
		return this.companyname;
	}

	public void setCompanyname(String companyname) {
		this.companyname = companyname;
	}

	public String getContactperson() {
		return this.contactperson;
	}

	public void setContactperson(String contactperson) {
		this.contactperson = contactperson;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}
	
	/**
	 * @return the domainname
	 */
	public String getDomainname() {
		return domainname;
	}

	/**
	 * @param domainname the domainname to set
	 */
	public void setDomainname(String domainname) {
		this.domainname = domainname;
	}

	public String getChargestring() {
		return this.chargestring;
	}

	public void setChargestring(String chargestring) {
		this.chargestring = chargestring;
	}

	public BigDecimal getLocked() {
		return this.locked;
	}

	public void setLocked(BigDecimal locked) {
		this.locked = locked;
	}

	public BigDecimal getEnableforcedonnet() {
		return this.enableforcedonnet;
	}

	public void setEnableforcedonnet(BigDecimal enableforcedonnet) {
		this.enableforcedonnet = enableforcedonnet;
	}

	public BigDecimal getEnablegrouphunting() {
		return this.enablegrouphunting;
	}

	public void setEnablegrouphunting(BigDecimal enablegrouphunting) {
		this.enablegrouphunting = enablegrouphunting;
	}

	public BigDecimal getEnableprivatecall() {
		return this.enableprivatecall;
	}

	public void setEnableprivatecall(BigDecimal enableprivatecall) {
		this.enableprivatecall = enableprivatecall;
	}

	public String getCompanycli() {
		return this.companycli;
	}

	public void setCompanycli(String companycli) {
		this.companycli = companycli;
	}

	public String getUsemaincliprefix() {
		return this.usemaincliprefix;
	}

	public void setUsemaincliprefix(String usemaincliprefix) {
		this.usemaincliprefix = usemaincliprefix;
	}

	public BigDecimal getClioption() {
		return this.clioption;
	}

	public void setClioption(BigDecimal clioption) {
		this.clioption = clioption;
	}
	
	
	/**
	 * @return the enablevpnchargingforsms
	 */
	public BigDecimal getEnablevpnchargingforsms() {
		return enablevpnchargingforsms;
	}

	/**
	 * @param enablevpnchargingforsms the enablevpnchargingforsms to set
	 */
	public void setEnablevpnchargingforsms(BigDecimal enablevpnchargingforsms) {
		this.enablevpnchargingforsms = enablevpnchargingforsms;
	}

	public String getDefaultincs() {
		return this.defaultincs;
	}

	public void setDefaultincs(String defaultincs) {
		this.defaultincs = defaultincs;
	}

	public String getDefaultincsdesc() {
		return this.defaultincsdesc;
	}

	public void setDefaultincsdesc(String defaultincsdesc) {
		this.defaultincsdesc = defaultincsdesc;
	}

	public String getBypassdefaultincs() {
		return this.bypassdefaultincs;
	}

	public void setBypassdefaultincs(String bypassdefaultincs) {
		this.bypassdefaultincs = bypassdefaultincs;
	}

	public String getForcedincs() {
		return this.forcedincs;
	}

	public void setForcedincs(String forcedincs) {
		this.forcedincs = forcedincs;
	}

	public String getForcedincsdesc() {
		return this.forcedincsdesc;
	}

	public void setForcedincsdesc(String forcedincsdesc) {
		this.forcedincsdesc = forcedincsdesc;
	}

	public String getBypassforcedincs() {
		return this.bypassforcedincs;
	}

	public void setBypassforcedincs(String bypassforcedincs) {
		this.bypassforcedincs = bypassforcedincs;
	}

	public String getDefaultoutcs() {
		return this.defaultoutcs;
	}

	public void setDefaultoutcs(String defaultoutcs) {
		
		this.defaultoutcs = defaultoutcs;
	}

	public String getDefaultoutcsdesc() {
		return this.defaultoutcsdesc;
	}

	public void setDefaultoutcsdesc(String defaultoutcsdesc) {
		this.defaultoutcsdesc = defaultoutcsdesc;
	}

	public String getBypassdefaultoutcs() {
		return this.bypassdefaultoutcs;
	}

	public void setBypassdefaultoutcs(String bypassdefaultoutcs) {
		this.bypassdefaultoutcs = bypassdefaultoutcs;
	}

	public String getForcedoutcs() {
		return this.forcedoutcs;
	}

	public void setForcedoutcs(String forcedoutcs) {
		this.forcedoutcs = forcedoutcs;
	}

	public String getForcedoutcsdesc() {
		return this.forcedoutcsdesc;
	}

	public void setForcedoutcsdesc(String forcedoutcsdesc) {
		this.forcedoutcsdesc = forcedoutcsdesc;
	}

	public String getBypassforcedoutcs() {
		return this.bypassforcedoutcs;
	}

	public void setBypassforcedoutcs(String bypassforcedoutcs) {
		this.bypassforcedoutcs = bypassforcedoutcs;
	}

	public String getUpdateuser() {
		return this.updateuser;
	}

	public void setUpdateuser(String updateuser) {
		this.updateuser = updateuser;
	}

	public Timestamp getUpdatetimestamp() {
		return this.updatetimestamp;
	}

	public void setUpdatetimestamp(Timestamp updatetimestamp) {
		this.updatetimestamp = updatetimestamp;
	}
	

}
