package com.nsn.telkomsel.mics.orahbm;

// Generated May 9, 2013 1:29:08 PM by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;
import java.math.BigDecimal;

/**
 * Huntingmember generated by hbm2java
 */
public class Huntingmember implements java.io.Serializable {


	private static final long serialVersionUID = 496237030211341308L;
	private String huntingmemberkey;
	private String huntingschedulekey;
	private String targetnumber;
	private BigDecimal orderindex;
	private String lastanswer;
	private String updateuser;
	private Timestamp updatetimestamp;

	public Huntingmember() {
	}

	public Huntingmember(String huntingmemberkey, String huntingschedulekey,
			String updateuser, Timestamp updatetimestamp) {
		this.huntingmemberkey = huntingmemberkey;
		this.huntingschedulekey = huntingschedulekey;
		this.updateuser = updateuser;
		this.updatetimestamp = updatetimestamp;
	}

	public Huntingmember(String huntingmemberkey, String huntingschedulekey,
			String targetnumber, BigDecimal orderindex, String lastanswer,
			String updateuser, Timestamp updatetimestamp) {
		this.huntingmemberkey = huntingmemberkey;
		this.huntingschedulekey = huntingschedulekey;
		this.targetnumber = targetnumber;
		this.orderindex = orderindex;
		this.lastanswer = lastanswer;
		this.updateuser = updateuser;
		this.updatetimestamp = updatetimestamp;
	}

	public String getHuntingmemberkey() {
		return this.huntingmemberkey;
	}

	public void setHuntingmemberkey(String huntingmemberkey) {
		this.huntingmemberkey = huntingmemberkey;
	}

	public String getHuntingschedulekey() {
		return this.huntingschedulekey;
	}

	public void setHuntingschedulekey(String huntingschedulekey) {
		this.huntingschedulekey = huntingschedulekey;
	}

	public String getTargetnumber() {
		return this.targetnumber;
	}

	public void setTargetnumber(String targetnumber) {
		this.targetnumber = targetnumber;
	}

	public BigDecimal getOrderindex() {
		return this.orderindex;
	}

	public void setOrderindex(BigDecimal orderindex) {
		this.orderindex = orderindex;
	}

	public String getLastanswer() {
		return this.lastanswer;
	}

	public void setLastanswer(String lastanswer) {
		this.lastanswer = lastanswer;
	}

	public String getUpdateuser() {
		return this.updateuser;
	}

	public void setUpdateuser(String updateuser) {
		this.updateuser = updateuser;
	}

	public Timestamp getUpdatetimestamp() {
		return this.updatetimestamp;
	}

	public void setUpdatetimestamp(Timestamp updatetimestamp) {
		this.updatetimestamp = updatetimestamp;
	}

}
